config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/new'
  get 'categories/show'
  get 'categories/create'
  get 'categories/destroy'
  root 'product#index'
  get 'products', to: 'product#index', as: 'products'
  get 'products/:id', to: 'product#show', as: 'product', id: /\d+/
  resources :categories do
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, presence: true
  validates :price, numericality: true
  validates :description, length: { minimun: 5, maximum: 300 }
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_param)
    if @category.save!
      redirect_to @category
    else
      render 'edit'
    end

  end

  def destroy
  end

  private

  def category_param
    params.require(:category).permit(:name)
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  
  def index
    @products = Product.order("name").page(params[:page]).per(5)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def helper
    @helper ||= Class.new do
      include ActionView::Helpers::NumberHelper
    end.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<div class="row py-5">

  <%= render 'shared/content_header',  header: 'Product Categories'  %>
  <div class="col-12">
    <%= render 'shared/content_table', table_headers: ['id','name', 'actions'], categories: @categories %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="row ">
  <div class="col-8 bg-white py-3 mx-auto">
    <h1 class="text-center"> Add New Category</h1>
    <hr>
      <%= form_with model: @category, local: true do |form|%>
        <div class="form-group col-8 mx-auto">
          <%= form.label :name, class:' font-weight-bold' %>
          <%= form.text_field :name, class:'form-control'%>
        </div>
        <div class="form-group col-8 mx-auto">
          <%= form.submit %>
        </div>
      <% end %>

  </div>
</div>

app/views/categories/show.html.erb
<div class="row bg-white">
<div class="col-10 mx-auto">
  <h1 class="text-center mb-3">
    Category Deatails
  </h1 >
  <h1 class="text-center text-muted">
    <%= @category.name%>
  </h1>
  <%= link_to 'Edit', edit_category_path, class: 'btn btn-info' %>
  <%= link_to 'Delete', edit_category_path, class: 'btn btn-danger' %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Estore</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application' , 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <%= render 'product/header' %>
  <%= yield %>
  </div>
</body>

</html>

app/views/product/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%=link_to 'Sasti Shop', root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%=link_to 'Home', root_path, class:'nav-link' %>
      </li>
            <li class="nav-item">
      <%=link_to 'Categories', categories_path, class:'nav-link' %>
      </li>
   <li class="nav-item ">
      <%=link_to 'Products', products_path, class:'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/product/_product.html.erb
<h2>
      <%= product.name%>
    </h2>
    <p>
      <%= product.description%>
    </p>
    <p><strong>
        <%= number_to_currency(product.price, unit: "Rs" )%>
      </strong></p>
    <%= link_to 'Show Details' , product_path(product) %>

app/views/product/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/product/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/product/index.html.erb
<div class="row">
<div class="col-10 mx-auto">
<%= paginate @products %>

<%= render 'shared/content_header',header: 'Products' %>

<%= render partial: "product", collection: @products %>



</div>

app/views/product/new.html.erb
<h1>Product#new</h1>
<p>Find me in app/views/product/new.html.erb</p>

app/views/product/show.html.erb
<h2>
  <%= @product.name%>
</h2>
<p>
  <%= @product.description%>
</p>
<p>
<strong>
    <%= number_to_currency(@product.price, unit: "Rs" ) %>
</strong>
</p>
<%=link_to 'Back' , products_path%>

app/views/shared/_content_header.html.erb
<div class="content-page-header col-12 py-3 pb-5">
    <h2 class="text-center font-weight-bold"><%= header %></h2>
    <%=link_to 'Add New Category', new_category_path, class:'btn btn-success d-block col-3 ml-auto' %>
</div>

app/views/shared/_content_table.html.erb
<table class="table">
  <%= render 'shared/table_header', table_headers: table_headers %>

            <tbody>
              <% categories.each do |category| %>
               <tr>
                <th scope="row"><%= category.id%></th>
                <td><%= category.name%></td>
                <td>
                  <%= link_to 'Details', category, class: 'btn btn-info'  %>
                  <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-secondary'  %>
                  <%= link_to 'Delete', category, class: 'btn btn-danger'  %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>

app/views/shared/_table_header.html.erb
<tbody>
  <tr>
    <% table_headers.each do |header_name| %>
    <th><%= header_name%></th>
    <% end %>
  </tr>
</tbody>